### ISSUE TITLE
how to access r, g, b, a ints from a color

### ISSUE THREAD

**Issue by phanirithvij** [RobCherry/vibrant#2]
I'm doing something like this.

```go
	log.Println(palette.VibrantSwatch().Color())
	r, g, b, a := palette.VibrantSwatch().Color().RGBA()
	log.Println(r, g, b, a)
```

It outputs

```
{248 160 24 255}
63736 41120 6168 65535
```
These are not in 0, 255 ?

**Comment by phanirithvij** [comment]
Do I need to do something like this? `log.Println(float32(r) / float32(a) * 255)`

**Comment by RobCherry** [comment]
This is using the standard [color.Color](https://golang.org/pkg/image/color/#Color) interface, so it is returning a 16-bit value.  You can use the following to get to the 8-bit RGBA values:

```go
c := palette.VibrantSwatch().Color()
nrgbaColor := color.NRGBAModel.Convert(c).(color.NRGBA)
// Then you can use that color...
r := nrgbaColor.R // uint8
g := nrgbaColor.G // uint8
b := nrgbaColor.B // uint8
a := nrgbaColor.A // uint8
// or
log.Printf("%d %d %d %d", nrgbaColor.R, nrgbaColor.G, nrgbaColor.B, nrgbaColor.A)

r2, g2, b2, a2 := nrgbaColor.RGBA() // uint32 in this case, but with a 16-bit value per the color.Color interface.
```

Let me know if that helps.

Edit: Link to the [color.Model](https://golang.org/pkg/image/color/#Model) documentation.

**Comment by phanirithvij** [comment]
Color has no R, G, B, A exposed.
So the above code you've given doesn't work (?)

```go
color.NRGBAModel.Convert(d.Color()).R undefined (type color.Color has no field or method R)
```

Color interface has only this method.
```go
type Color interface {
	// RGBA returns the alpha-premultiplied red, green, blue and alpha values
	// for the color. Each value ranges within [0, 0xffff], but is represented
	// by a uint32 so that multiplying by a blend factor up to 0xffff will not
	// overflow.
	//
	// An alpha-premultiplied color component c has been scaled by alpha (a),
	// so has valid values 0 <= c <= a.
	RGBA() (r, g, b, a uint32)
}

```

**Comment by RobCherry** [comment]
You are correct, I didn't test the code and left out something... Cast the result of the `Convert` call to a `color.NRGBA`.

I have updated the code sample I provided (still untested, but it should work).
